name: heroku-deploy

on:
  push:
    branches: [master]

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.8.9
        with:
          heroku-api-key: ${{secrets.HEROKU_API_TOKEN}}
          heroku-app-name: "gh-action-test"
          heroku-email: "ac380012@gmail.com"
